-- generated by matugen from the current wallpaper -- edit the template in ~/.config/matugen/templates
return {
  base00 = "{{colors.surface_container_low.default.hex}}",
  base01 = "{{colors.surface_container_highest.default.hex}}",
  base02 = "{{colors.outline_variant.default.hex}}",
  base03 = "{{colors.outline.default.hex}}",
  base04 = "{{colors.on_surface_variant.default.hex}}",
  base05 = "{{colors.on_surface.default.hex}}",
  base06 = "{{colors.on_surface.default.hex | lighten: 5}}",
  base07 = "{{colors.primary_fixed.default.hex}}",
  base08 = "{{colors.red.default.hex}}",
  base09 = "{{colors.peach.default.hex}}",
  base0A = "{{colors.yellow.default.hex}}",
  base0B = "{{colors.green.default.hex}}",
  base0C = "{{colors.teal.default.hex}}",
  base0D = "{{colors.blue.default.hex}}",
  base0E = "{{colors.primary.default.hex}}",
  base0F = "{{colors.flamingo.default.hex}}",
}
