-- generated by ~/.config/theme/theme ({{name}}) -- edit the template in ~/.config/theme/templates
-- colorscheme: a real nvim colorscheme for presets; empty for the wallpaper
-- theme, which uses the base16 table instead
return {
  colorscheme = "{{nvim}}",
  base16 = {
    base00 = "{{base}}",
    base01 = "{{surface0}}",
    base02 = "{{surface1}}",
    base03 = "{{overlay2}}",
    base04 = "{{subtext1}}",
    base05 = "{{text}}",
    base06 = "{{text | lighten: 5}}",
    base07 = "{{lavender}}",
    base08 = "{{red}}",
    base09 = "{{peach}}",
    base0A = "{{yellow}}",
    base0B = "{{green}}",
    base0C = "{{teal}}",
    base0D = "{{blue}}",
    base0E = "{{accent}}",
    base0F = "{{flamingo}}",
  },
}
