# for more info: https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/

general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = pidof hyprlock || hyprlock # lock before suspend/sleep
    after_sleep_cmd = hyprctl dispatch dpms on   # turn monitors back on after resuming
}

listener {
    timeout = 300                                # 5 min
    on-timeout = pidof hyprlock || hyprlock       # lock screen
}

listener {
    timeout = 330                                # 5.5 min
    on-timeout = hyprctl dispatch dpms off        # turn off screen (after locking)
    on-resume = hyprctl dispatch dpms on          # turn on screen
}

listener {
    timeout = 900                                # 15 min
    on-timeout = [ "$(cat /sys/class/power_supply/ACAD/online 2>/dev/null)" = "0" ] && systemctl suspend    # suspend pc only if on battery
}
